export const SET_EMAIL = 'SET_EMAIL'
export const ADD_SCORE = 'ADD_SCORE'
// export const SET_USER = 'SET_USER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

export const SET_MESSAGE = 'SET_MESSAGE'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'
export const REMOVE_SCORE = 'REMOVE_SCORE'

// REGISTER A USER
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR'

// LOGIN A USER
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'
export const USER_LOGOUT = 'USER_LOGOUT'

// GET A USER
export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_ERROR = 'GET_USER_ERROR'

// QUIZ RESULTS
export const QUIZ_RESULTS_REQUEST = 'QUIZ_RESULTS_REQUEST'
export const QUIZ_RESULTS_SUCCESS = 'QUIZ_RESULTS_SUCCESS'
export const QUIZ_RESULTS_ERROR = 'QUIZ_RESULTS_ERROR'

// SET USER CAREERPATH
export const SET_CAREER_REQUEST = 'SET_CAREER_REQUEST'
export const SET_CAREER_SUCCESS = 'SET_CAREER_SUCCESS'
export const SET_CAREER_ERROR = 'SET_CAREER_ERROR'

// USER UTILITY TYPES
export const CLEAR_USER_ERRORS = 'CLEAR_USER_ERRORS'
export const CLEAR_USER_MESSAGES = 'CLEAR_USER_MESSAGES'
